name = "GeodesicLearning"
uuid = "e188284a-cc59-4f25-aa57-2925a018b9ec"
authors = ["Colin LaMont"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
